import { createHash, randomUUID } from 'node:crypto';
import { FieldValue } from 'firebase-admin/firestore';
import { URL } from 'node:url';

export const RESEARCH_CATEGORIES = ['identification', 'engine', 'transmission', 'chassis', 'brakes', 'wheels', 'tyres', 'fluids', 'maintenance', 'strengths', 'weaknesses', 'issues', 'risks', 'modifications', 'compatibilities', 'reasonable_limits', 'year_market_differences'];
export const RESEARCH_STAGES = ['queued', 'normalizing', 'identifying', 'ambiguity_check', 'collecting_sources', 'contrasting', 'structuring', 'persisting_sources', 'scoring_confidence', 'detecting_contradictions', 'awaiting_human_review', 'approved', 'publishing', 'published', 'failed'];
const CRITICAL_CATEGORIES = new Set(['identification', 'engine', 'transmission', 'brakes', 'wheels', 'tyres', 'fluids', 'reasonable_limits']);
const ALLOWED_SOURCE_TYPES = new Set(['manufacturer_manual', 'parts_catalogue', 'regulation', 'technical_database', 'specialist', 'community_forum', 'other']);

/**
 * Connector contract: `{ id: string, collect(request): Promise<SourceCandidate[]> }`.
 * Connectors fetch externally; this pipeline only accepts validated, atomic claims and source metadata.
 */

export function normalizeVehicleResearchRequest(value) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('La solicitud de investigación no es válida.');
  const request = { brand: text(value.brand, 80, true), model: text(value.model, 100, true), generation: text(value.generation, 100), variant: text(value.variant, 140), year: integer(value.year, 1886, new Date().getUTCFullYear() + 1), market: text(value.market, 80), engineCode: upperCode(value.engineCode), transmissionCode: upperCode(value.transmissionCode) };
  const ambiguities = detectVehicleAmbiguities(request);
  const lookupKey = [request.brand, request.model, request.generation, request.variant, request.year || '', request.market, request.engineCode, request.transmissionCode].map(normalizeKey).join('|');
  return { ...request, lookupKey, precision: ambiguities.length === 0 ? 'exact' : ambiguities.some((item) => item.severity === 'critical') ? 'ambiguous' : 'probable', ambiguities };
}

export function detectVehicleAmbiguities(request) {
  const ambiguities = [];
  if (!request.generation) ambiguities.push({ field: 'generation', severity: 'critical', message: 'Falta la generación exacta.' });
  if (!request.variant) ambiguities.push({ field: 'variant', severity: 'critical', message: 'Falta la versión o acabado exacto.' });
  if (!request.year) ambiguities.push({ field: 'year', severity: 'high', message: 'Falta el año, necesario para detectar revisiones.' });
  if (!request.market) ambiguities.push({ field: 'market', severity: 'high', message: 'Falta el mercado, que puede cambiar motor, emisiones y equipamiento.' });
  if (!request.engineCode) ambiguities.push({ field: 'engineCode', severity: 'high', message: 'Código de motor pendiente de confirmar.' });
  return ambiguities;
}

export async function ensureVehicleResearchJob({ db, ownerId, projectId, userVehicleId, request }) {
  const normalized = normalizeVehicleResearchRequest(request); const hash = createHash('sha256').update(normalized.lookupKey).digest('hex');
  const id = `vehicle_research_${hash.slice(0, 32)}`; const reference = db.collection('aiRuns').doc(id); const now = new Date();
  await db.runTransaction(async (transaction) => { const snapshot = await transaction.get(reference); if (snapshot.exists && !['failed', 'cancelled', 'rejected'].includes(snapshot.data()?.stage)) { transaction.set(reference, { ownerIds: FieldValue.arrayUnion(ownerId), projectIds: FieldValue.arrayUnion(projectId), userVehicleIds: FieldValue.arrayUnion(userVehicleId), updatedAt: now }, { merge: true }); return; } transaction.set(reference, { ownerId, ownerIds: [ownerId], projectId, projectIds: [projectId], userVehicleId, userVehicleIds: [userVehicleId], purpose: 'master_data_research', targetType: 'vehicle_master', targetId: hash.slice(0, 32), contextHash: hash, normalizedRequest: normalized, status: 'queued', stage: 'queued', sourceIds: [], connectorIds: [], confidence: { level: 'unverified', rationale: 'Investigación pendiente.', assessedBy: 'system', assessedAt: now }, reviewStatus: 'draft', reopenCount: snapshot.exists ? Number(snapshot.data()?.reopenCount || 0) + 1 : 0, schemaVersion: 1, createdAt: snapshot.data()?.createdAt || now, updatedAt: now }); });
  return { id, normalizedRequest: normalized };
}

export async function runVehicleResearchPipeline({ db, jobId, connectors, now = new Date() }) {
  const reference = db.collection('aiRuns').doc(safeId(jobId)); const snapshot = await reference.get(); if (!snapshot.exists) throw new Error('ResearchJob no encontrado.');
  const job = snapshot.data(); if (job.purpose !== 'master_data_research') throw new Error('El job no corresponde a investigación maestra.');
  if (!['queued', 'failed', 'changes_requested'].includes(job.stage)) throw new Error(`El job no puede ejecutarse desde el estado ${job.stage}.`);
  const request = normalizeVehicleResearchRequest(job.normalizedRequest); const connectorList = Array.isArray(connectors) ? connectors : [];
  if (!connectorList.length) throw new Error('No hay conectores de investigación configurados.');
  await stage(reference, 'normalizing', { status: 'running', startedAt: now, errorCode: FieldValue.delete() });
  try {
    await stage(reference, 'identifying', { normalizedRequest: request }); await stage(reference, 'ambiguity_check', { ambiguities: request.ambiguities });
    await stage(reference, 'collecting_sources', { connectorIds: connectorList.map((connector) => safeId(connector.id)) });
    const collected = await collectResearchSources(connectorList, request);
    await stage(reference, 'contrasting', { collectedSourceCount: collected.length }); const scoped = enforceVehicleScope(collected, request);
    await stage(reference, 'structuring', { excludedClaimCount: scoped.excludedClaims.length });
    await stage(reference, 'persisting_sources'); const sourceMap = await persistSources(db, scoped.sources, now);
    await stage(reference, 'scoring_confidence'); const analysis = analyzeResearchClaims(scoped.sources, sourceMap, request, now);
    await stage(reference, 'detecting_contradictions', { contradictionCount: analysis.contradictions.length });
    const resultReference = db.collection('vehicleResearchResults').doc(randomUUID()); const reviewReference = db.collection('reviewTasks').doc(randomUUID()); const batch = db.batch();
    for (const claim of analysis.claims) batch.set(db.collection('technicalClaims').doc(claim.id), claim);
    for (const contradiction of analysis.contradictions) batch.set(db.collection('researchContradictions').doc(contradiction.id), contradiction);
    batch.set(resultReference, { jobId, normalizedRequest: request, claimIds: analysis.claims.map((claim) => claim.id), sourceIds: [...sourceMap.values()], contradictionIds: analysis.contradictions.map((item) => item.id), excludedClaims: scoped.excludedClaims.slice(0, 100), blockingIssues: analysis.blockingIssues, categories: RESEARCH_CATEGORIES, status: 'awaiting_human_review', schemaVersion: 1, createdAt: now, updatedAt: now });
    batch.set(reviewReference, { type: 'vehicle_research', jobId, resultId: resultReference.id, status: 'open', priority: request.precision === 'ambiguous' || analysis.contradictions.length ? 'high' : 'normal', ambiguityCount: request.ambiguities.length, contradictionCount: analysis.contradictions.length, blockingIssueCount: analysis.blockingIssues.length, requiredRole: 'reviewer', schemaVersion: 1, createdAt: now, updatedAt: now });
    batch.set(reference, { resultId: resultReference.id, reviewTaskId: reviewReference.id, sourceIds: [...sourceMap.values()], status: 'validating', stage: 'awaiting_human_review', reviewStatus: 'in_review', confidence: analysis.overallConfidence, updatedAt: now }, { merge: true }); await batch.commit();
    return { jobId, resultId: resultReference.id, reviewTaskId: reviewReference.id, ...analysis };
  } catch (error) { await reference.set({ status: 'failed', stage: 'failed', errorCode: String(error.code || error.name || 'research_failed').slice(0, 100), errorMessage: String(error.message || 'Error de investigación').slice(0, 500), updatedAt: new Date() }, { merge: true }); throw error; }
}

export async function approveVehicleResearch({ db, jobId, reviewerId, decisionNotes }) {
  const jobReference = db.collection('aiRuns').doc(safeId(jobId)); const now = new Date(); const notes = text(decisionNotes, 1000);
  await db.runTransaction(async (transaction) => { const snapshot = await transaction.get(jobReference); if (!snapshot.exists || snapshot.data()?.stage !== 'awaiting_human_review') throw new Error('La investigación no está pendiente de revisión.'); const job = snapshot.data(); const resultReference = db.collection('vehicleResearchResults').doc(job.resultId); const resultSnapshot = await transaction.get(resultReference); if (!resultSnapshot.exists || resultSnapshot.data()?.blockingIssues?.length) throw new Error('La investigación mantiene bloqueos que deben resolverse antes de aprobar.'); const reviewReference = db.collection('reviewTasks').doc(job.reviewTaskId); for (const claimId of resultSnapshot.data().claimIds || []) transaction.set(db.collection('technicalClaims').doc(claimId), { reviewStatus: 'approved', reviewedBy: reviewerId, reviewedAt: now, updatedAt: now }, { merge: true }); for (const sourceId of resultSnapshot.data().sourceIds || []) transaction.set(db.collection('sources').doc(sourceId), { status: 'accepted', reviewedBy: reviewerId, reviewedAt: now, updatedAt: now }, { merge: true }); transaction.set(reviewReference, { status: 'approved', reviewedBy: reviewerId, reviewedAt: now, ...(notes ? { decisionNotes: notes } : {}), updatedAt: now }, { merge: true }); transaction.set(resultReference, { status: 'approved', reviewedBy: reviewerId, reviewedAt: now, updatedAt: now }, { merge: true }); transaction.set(jobReference, { stage: 'approved', status: 'completed', reviewStatus: 'approved', reviewedBy: reviewerId, reviewedAt: now, completedAt: now, updatedAt: now }, { merge: true }); });
}

export async function publishApprovedVehicleResearch({ db, jobId, publisherId }) {
  const jobReference = db.collection('aiRuns').doc(safeId(jobId)); const now = new Date();
  return db.runTransaction(async (transaction) => { const snapshot = await transaction.get(jobReference); if (!snapshot.exists || snapshot.data()?.stage !== 'approved' || snapshot.data()?.reviewStatus !== 'approved') throw new Error('Solo una investigación aprobada puede publicarse.'); const job = snapshot.data(); const resultReference = db.collection('vehicleResearchResults').doc(job.resultId); const resultSnapshot = await transaction.get(resultReference); if (!resultSnapshot.exists || resultSnapshot.data()?.status !== 'approved') throw new Error('El resultado aprobado no existe.'); const approvedClaims = []; for (const claimId of resultSnapshot.data().claimIds || []) { const claimSnapshot = await transaction.get(db.collection('technicalClaims').doc(claimId)); if (!claimSnapshot.exists || claimSnapshot.data()?.reviewStatus !== 'approved') throw new Error('Todas las afirmaciones deben estar aprobadas antes de publicar.'); approvedClaims.push({ id: claimSnapshot.id, ...claimSnapshot.data() }); } const revisionReference = db.collection('publishedRevisions').doc(); const projectionReference = db.collection('publishedVehicleResearch').doc(job.targetId); transaction.set(revisionReference, { entityType: 'vehicle_research', entityKey: job.normalizedRequest.lookupKey, jobId, resultId: job.resultId, claimIds: resultSnapshot.data().claimIds, sourceIds: resultSnapshot.data().sourceIds, status: 'published', publishedBy: publisherId, publishedAt: now, schemaVersion: 1, createdAt: now, updatedAt: now }); transaction.set(projectionReference, { normalizedLookupKey: job.normalizedRequest.lookupKey, identity: job.normalizedRequest, claims: approvedClaims.map((claim) => ({ id: claim.id, category: claim.category, fieldPath: claim.fieldPath, value: claim.value, unit: claim.unit || null, sourceIds: claim.sourceIds, confidence: claim.confidence })), sourceIds: resultSnapshot.data().sourceIds, revisionId: revisionReference.id, status: 'published', publishedAt: now, schemaVersion: 1, createdAt: now, updatedAt: now }, { merge: true }); transaction.set(resultReference, { status: 'published', publishedRevisionId: revisionReference.id, updatedAt: now }, { merge: true }); transaction.set(jobReference, { stage: 'published', status: 'completed', reviewStatus: 'published', publishedRevisionId: revisionReference.id, updatedAt: now }, { merge: true }); return { revisionId: revisionReference.id, projectionId: projectionReference.id }; });
}

export async function reopenVehicleResearch({ db, jobId, reviewerId, reason }) { const reference = db.collection('aiRuns').doc(safeId(jobId)); const now = new Date(); await db.runTransaction(async (transaction) => { const snapshot = await transaction.get(reference); if (!snapshot.exists || !['awaiting_human_review', 'approved', 'published', 'failed'].includes(snapshot.data()?.stage)) throw new Error('La investigación no se puede reabrir desde su estado actual.'); transaction.set(reference, { stage: 'queued', status: 'queued', reviewStatus: 'changes_requested', reopenedBy: reviewerId, reopenReason: text(reason, 1000, true), reopenCount: FieldValue.increment(1), updatedAt: now }, { merge: true }); }); }

export function analyzeResearchClaims(sources, sourceMap, request, now) {
  const grouped = new Map(); for (const source of sources) for (const claim of source.claims) { const comparisonScope = claim.category === 'year_market_differences' ? `:${normalizeKey(claim.market)}:${String(claim.year || '')}` : ''; const key = `${claim.category}:${claim.fieldPath}${comparisonScope}`; const current = grouped.get(key) || []; current.push({ ...claim, source }); grouped.set(key, current); }
  const claims = []; const contradictions = []; const blockingIssues = [];
  for (const [key, entries] of grouped) { const values = new Map(); for (const entry of entries) { const canonical = canonicalValue(entry.value); const group = values.get(canonical) || []; group.push(entry); values.set(canonical, group); } const reliableValues = [...values.entries()].filter(([, items]) => items.some((item) => item.source.trustTier !== 'community')); const hasContradiction = reliableValues.length > 1; if (hasContradiction) contradictions.push({ id: randomUUID(), jobLookupKey: request.lookupKey, fieldKey: key, values: reliableValues.map(([value, items]) => ({ value, sourceKeys: items.map((item) => item.source.sourceKey) })), status: 'open', detectedAt: now, schemaVersion: 1, createdAt: now, updatedAt: now }); const best = [...values.values()].sort((a, b) => scoreEvidence(b) - scoreEvidence(a))[0]; if (!best) continue; const sourceIds = [...new Set(best.map((item) => sourceMap.get(item.source.sourceKey)).filter(Boolean))]; const confidence = fieldConfidence(best, hasContradiction); const category = best[0].category; const fieldPath = best[0].fieldPath; const communityOnlyCritical = CRITICAL_CATEGORIES.has(category) && best.every((item) => item.source.trustTier === 'community'); if (communityOnlyCritical) blockingIssues.push(`El campo crítico ${key} solo está respaldado por comunidad/foro.`); if (hasContradiction) blockingIssues.push(`Contradicción fiable pendiente en ${key}.`); claims.push({ id: randomUUID(), entityType: 'vehicle_master', entityKey: request.lookupKey, category, fieldPath, value: best[0].value, ...(best[0].unit ? { unit: best[0].unit } : {}), scope: { generation: best[0].generation || request.generation, market: best[0].market || request.market, year: best[0].year || request.year, engineCode: upperCode(best[0].engineCode) || request.engineCode }, sourceIds, confidence, contradictionIds: contradictions.filter((item) => item.fieldKey === key).map((item) => item.id), reviewStatus: 'in_review', schemaVersion: 1, createdAt: now, updatedAt: now }); }
  const levels = claims.map((claim) => claim.confidence.level); const overallLevel = blockingIssues.length ? 'low' : levels.length && levels.every((level) => ['high', 'verified'].includes(level)) ? 'high' : levels.some((level) => ['medium', 'high', 'verified'].includes(level)) ? 'medium' : levels.length ? 'low' : 'unverified';
  return { claims, contradictions, blockingIssues: [...new Set(blockingIssues)], overallConfidence: { level: overallLevel, rationale: blockingIssues.length ? 'Existen contradicciones o fuentes insuficientes en campos críticos.' : 'Confianza agregada a partir de fuentes independientes.', assessedBy: 'system', assessedAt: now } };
}

export async function collectResearchSources(connectors, request) { const collected = []; let claimCount = 0; for (const connector of connectors) { const output = await connector.collect({ ...request, categories: RESEARCH_CATEGORIES }); validateConnectorOutput(output, connector.id); collected.push(...output.map((item) => ({ ...item, connectorId: connector.id }))); claimCount += output.reduce((total, item) => total + item.claims.length, 0); if (collected.length > 100 || claimCount > 200) throw new Error('Los conectores superaron el límite seguro de fuentes o afirmaciones por job.'); } return collected; }

export function enforceVehicleScope(sources, request) { const accepted = []; const excludedClaims = []; for (const source of sources) { const claims = []; for (const claim of source.claims) { const comparative = claim.category === 'year_market_differences'; const mismatch = !comparative && ((claim.generation && normalizeKey(claim.generation) !== normalizeKey(request.generation)) || (claim.market && request.market && normalizeKey(claim.market) !== normalizeKey(request.market)) || (claim.engineCode && request.engineCode && upperCode(claim.engineCode) !== request.engineCode)); if (mismatch) excludedClaims.push({ sourceKey: source.sourceKey, category: claim.category, fieldPath: claim.fieldPath, reason: 'scope_mismatch' }); else claims.push(claim); } if (claims.length) accepted.push({ ...source, claims }); } return { sources: accepted, excludedClaims }; }
async function persistSources(db, sources, now) { const map = new Map(); const batch = db.batch(); for (const source of sources) { if (map.has(source.sourceKey)) continue; const id = createHash('sha256').update(source.sourceKey).digest('hex').slice(0, 32); map.set(source.sourceKey, id); const publisher = text(source.publisher, 200); const market = text(source.market, 80); const notes = text(source.notes, 500); batch.set(db.collection('sources').doc(id), { title: text(source.title, 300, true), type: source.type, ...(publisher ? { publisher } : {}), ...(source.url ? { url: source.url } : {}), ...(source.documentStoragePath ? { documentStoragePath: source.documentStoragePath } : {}), ...(market ? { market } : {}), ...(source.publishedAt ? { publishedAt: source.publishedAt } : {}), accessedAt: source.accessedAt || now, status: 'pending_review', ...(notes ? { notes } : {}), connectorId: source.connectorId, trustTier: source.trustTier, schemaVersion: 1, createdAt: now, updatedAt: now }, { merge: true }); } if (map.size) await batch.commit(); return map; }
function validateConnectorOutput(output, connectorId) { if (!Array.isArray(output)) throw new Error(`El conector ${connectorId} no devolvió una lista.`); for (const source of output) { if (!source || typeof source !== 'object' || !ALLOWED_SOURCE_TYPES.has(source.type) || !['primary', 'secondary', 'community'].includes(source.trustTier) || !isSafeSourceLocation(source) || !Array.isArray(source.claims)) throw new Error(`Salida no válida del conector ${connectorId}.`); source.sourceKey = String(source.sourceKey || source.url || source.documentStoragePath); for (const claim of source.claims) if (!RESEARCH_CATEGORIES.includes(claim.category) || !text(claim.fieldPath, 200) || !isClaimValue(claim.value)) throw new Error(`Claim no válido del conector ${connectorId}.`); } }
function fieldConfidence(entries, contradiction) { const tiers = new Set(entries.map((item) => item.source.trustTier)); const publishers = new Set(entries.map((item) => normalizeKey(item.source.publisher || item.source.sourceKey))); const level = contradiction ? 'low' : tiers.has('primary') && publishers.size >= 2 ? 'high' : (tiers.has('primary') || tiers.has('secondary')) && publishers.size >= 2 ? 'medium' : tiers.has('community') && tiers.size === 1 ? 'unverified' : 'low'; return { level, rationale: contradiction ? 'Fuentes fiables discrepan.' : `${publishers.size} fuente(s) independiente(s); nivel ${[...tiers].join(', ')}.`, assessedBy: 'system', assessedAt: new Date() }; }
function scoreEvidence(entries) { return entries.reduce((total, item) => total + ({ primary: 4, secondary: 2, community: 0.5 }[item.source.trustTier] || 0), 0); }
async function stage(reference, nextStage, extra = {}) { if (!RESEARCH_STAGES.includes(nextStage)) throw new Error('Estado de investigación no válido.'); await reference.set({ stage: nextStage, updatedAt: new Date(), ...extra }, { merge: true }); }
function canonicalValue(value) { return JSON.stringify(value, Object.keys(value && typeof value === 'object' && !Array.isArray(value) ? value : {}).sort()); }
function normalizeKey(value) { return String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim().toLowerCase().replace(/\s+/g, ' '); }
function upperCode(value) { return text(value, 80).toUpperCase().replace(/\s+/g, ''); }
function integer(value, minimum, maximum) { const parsed = Number(value); return Number.isInteger(parsed) && parsed >= minimum && parsed <= maximum ? parsed : null; }
function text(value, maximum, required = false) { const result = typeof value === 'string' ? value.trim().slice(0, maximum) : ''; if (required && !result) throw new Error('Falta un campo obligatorio.'); return result; }
function safeId(value) { const id = String(value || '').trim(); if (!id || id.includes('/') || id.length > 200) throw new Error('Identificador no válido.'); return id; }
function isClaimValue(value) { if (typeof value === 'string') return value.trim().length > 0; if (typeof value === 'number') return Number.isFinite(value); if (typeof value === 'boolean') return true; if (!Array.isArray(value) || value.length === 0) return false; return value.every((item) => typeof item === 'string' && item.trim() || typeof item === 'number' && Number.isFinite(item)) && (value.every((item) => typeof item === 'string') || value.every((item) => typeof item === 'number')); }
function isSafeSourceLocation(source) { if (source.documentStoragePath && typeof source.documentStoragePath === 'string' && !source.documentStoragePath.includes('..')) return true; if (typeof source.url !== 'string') return false; try { const parsed = new URL(source.url); return ['http:', 'https:'].includes(parsed.protocol); } catch { return false; } }
