import { z } from 'zod';
import { auth } from '../../../firebase/config';

const preferencesSchema = z.object({ timezone: z.string(), categories: z.object({ maintenance: z.boolean(), research: z.boolean(), diagnostics: z.boolean(), vehicle_alerts: z.boolean() }), channels: z.object({ in_app: z.boolean(), push: z.boolean(), email: z.boolean() }), quietHours: z.object({ start: z.string(), end: z.string() }).nullable().optional() }).loose();
export type NotificationPreferencesInput = z.infer<typeof preferencesSchema>;
function apiBase(): string { const configured = String(import.meta.env.VITE_API_BASE_URL ?? '').replace(/\/$/, ''); if (typeof window !== 'undefined' && ['localhost', '127.0.0.1', '::1'].includes(window.location.hostname)) return 'http://127.0.0.1:8787'; return configured; }
async function authHeaders(): Promise<Record<string, string>> { if (!auth.currentUser) throw new Error('Inicia sesión para gestionar tus avisos.'); return { 'Content-Type': 'application/json', Authorization: `Bearer ${await auth.currentUser.getIdToken()}` }; }
async function parse(response: Response): Promise<unknown> { const body: unknown = await response.json().catch(() => null); if (!response.ok) throw new Error(typeof body === 'object' && body !== null && 'error' in body ? String(body.error) : 'No se pudo actualizar las notificaciones.'); return body; }
export async function loadNotificationPreferences(): Promise<NotificationPreferencesInput> { const response = await fetch(`${apiBase()}/api/premium/notifications/preferences`, { headers: await authHeaders() }); return preferencesSchema.parse(z.object({ preferences: z.unknown() }).parse(await parse(response)).preferences); }
export async function saveNotificationPreferences(preferences: NotificationPreferencesInput): Promise<NotificationPreferencesInput> { const response = await fetch(`${apiBase()}/api/premium/notifications/preferences`, { method: 'PATCH', headers: await authHeaders(), body: JSON.stringify(preferences) }); return preferencesSchema.parse(z.object({ preferences: z.unknown() }).parse(await parse(response)).preferences); }
export async function notifyDiagnosticAvailable(vehicleId: string, diagnosticId: string): Promise<void> { const response = await fetch(`${apiBase()}/api/premium/notifications/events/diagnostic-available`, { method: 'POST', headers: await authHeaders(), body: JSON.stringify({ vehicleId, diagnosticId }) }); await parse(response); }
