import { useRef, useState, type ChangeEvent, type SyntheticEvent } from 'react';
import type { Firestore } from 'firebase/firestore';
import type { FirebaseStorage } from 'firebase/storage';
import type { DiagnosticContext, DiagnosticEvidence, DiagnosticSession } from '../models';
import { ConservativeKnownIssuesProvider } from './diagnosticProvider';
import { createDiagnosticSession, deleteDiagnosticEvidence, type DiagnosticFileInput } from './diagnosticService';
import type { IssuesModuleData } from './issuesModuleData';

const provider = new ConservativeKnownIssuesProvider();
const PHASES: { value: DiagnosticContext['drivingPhases'][number]; label: string }[] = [{ value: 'starting', label: 'Al arrancar' }, { value: 'accelerating', label: 'Al acelerar' }, { value: 'braking', label: 'Al frenar' }, { value: 'turning', label: 'Al girar' }, { value: 'cruising', label: 'Circulando' }];

export function IssuesModule({ data, loading, error, firestore, storage, onRefresh }: { data: IssuesModuleData | null; loading: boolean; error?: string | null; firestore: Firestore; storage: FirebaseStorage; onRefresh: () => Promise<void> }) {
  const [view, setView] = useState<'issues' | 'diagnose' | 'history'>('issues');
  if (loading) return <IssuesSkeleton />;
  if (error) return <IssuesEmpty title="No se pudo cargar el módulo" copy={error} />;
  if (!data) return <IssuesEmpty title="Sin vehículo" copy="Completa el onboarding para utilizar Diagnostícate." />;
  return <section className="garage-module issues-module"><header className="garage-module-heading"><span>Fallos y averías</span><h1>Diagnostícate</h1><p>Organiza síntomas y evidencias para decidir el siguiente paso sin convertir una hipótesis en una avería confirmada.</p></header>
    <nav className="issues-tabs" aria-label="Secciones de diagnóstico"><button className={view === 'issues' ? 'active' : ''} type="button" onClick={() => { setView('issues'); }}>Riesgos conocidos</button><button className={view === 'diagnose' ? 'active' : ''} type="button" onClick={() => { setView('diagnose'); }}>Diagnostícate</button><button className={view === 'history' ? 'active' : ''} type="button" onClick={() => { setView('history'); }}>Historial</button></nav>
    {view === 'issues' && <KnownIssues data={data} onDiagnose={() => { setView('diagnose'); }} />}
    {view === 'diagnose' && <DiagnosticForm data={data} firestore={firestore} storage={storage} onCompleted={async () => { await onRefresh(); setView('history'); }} />}
    {view === 'history' && <DiagnosticHistory data={data} firestore={firestore} storage={storage} onRefresh={onRefresh} />}
  </section>;
}

function KnownIssues({ data, onDiagnose }: { data: IssuesModuleData; onDiagnose: () => void }) { return <section className="issues-known"><header><div><span>Vehículo analizado</span><h2>{data.vehicleContext.vehicle.variantSnapshot.brand} {data.vehicleContext.vehicle.variantSnapshot.model} {data.vehicleContext.vehicle.variantSnapshot.variant}</h2></div><button type="button" onClick={onDiagnose}>Describir un síntoma</button></header>{data.vehicleContext.knownIssues.length ? <div>{data.vehicleContext.knownIssues.map((issue) => <article key={issue.id}><span>{severityLabel(issue.severity)}</span><h3>{issue.title}</h3><p>{issue.symptoms.join(' · ')}</p><small>Fallo conocido documentado; no implica que esté presente en tu vehículo.</small></article>)}</div> : <IssuesEmpty title="Investigación pendiente" copy="No hay fallos conocidos aprobados para esta variante. No mostraremos datos genéricos." />}</section>; }

function DiagnosticForm({ data, firestore, storage, onCompleted }: { data: IssuesModuleData; firestore: Firestore; storage: FirebaseStorage; onCompleted: () => Promise<void> }) {
  const [files, setFiles] = useState<DiagnosticFileInput[]>([]); const [phases, setPhases] = useState<DiagnosticContext['drivingPhases']>([]); const [recording, setRecording] = useState(false); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState<string | null>(null);
  const recorderRef = useRef<MediaRecorder | null>(null); const chunksRef = useRef<Blob[]>([]); const recordingStartedAtRef = useRef(0); const recordingTimeoutRef = useRef<number | null>(null);
  async function toggleRecording() {
    if (recording) { recorderRef.current?.stop(); return; }
    try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const recorder = new MediaRecorder(stream, { audioBitsPerSecond: 64_000 }); recorderRef.current = recorder; chunksRef.current = []; recordingStartedAtRef.current = Date.now(); recorder.ondataavailable = (event) => { if (event.data.size) chunksRef.current.push(event.data); }; recorder.onstop = () => { if (recordingTimeoutRef.current !== null) window.clearTimeout(recordingTimeoutRef.current); recordingTimeoutRef.current = null; const type = (recorder.mimeType || 'audio/webm').split(';')[0]; const extension = type === 'audio/mp4' ? 'm4a' : type === 'audio/mpeg' ? 'mp3' : type === 'audio/wav' ? 'wav' : type === 'audio/ogg' ? 'ogg' : 'webm'; const durationSeconds = Math.min(60, Math.max(1, Math.round((Date.now() - recordingStartedAtRef.current) / 1000))); setFiles((current) => [...current, { blob: new Blob(chunksRef.current, { type }), name: `diagnostico-${String(Date.now())}.${extension}`, type: 'audio', durationSeconds }]); stream.getTracks().forEach((track) => { track.stop(); }); setRecording(false); }; recorder.start(1_000); recordingTimeoutRef.current = window.setTimeout(() => { if (recorder.state === 'recording') recorder.stop(); }, 60_000); setRecording(true); }
    catch { setFormError('No se pudo acceder al micrófono. Revisa el permiso del navegador.'); }
  }
  function addPhoto(event: ChangeEvent<HTMLInputElement>) { const selected = event.target.files?.[0]; if (selected) setFiles((current) => [...current, { blob: selected, name: selected.name, type: 'image' }]); event.target.value = ''; }
  async function submit(event: SyntheticEvent<HTMLFormElement, SubmitEvent>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const symptoms = stringField(form, 'symptoms'); const occurrence = stringField(form, 'occurrence');
    if (!occurrence || phases.length === 0) { setFormError('Indica cuándo ocurre y al menos una situación de conducción.'); return; }
    const temperature = stringField(form, 'temperature'); const severity = stringField(form, 'severity'); if (!isTemperature(temperature) || !isDeclaredSeverity(severity)) { setFormError('Revisa el contexto del síntoma.'); return; }
    const context: DiagnosticContext = { occurrence, engineTemperature: temperature, drivingPhases: phases, ...optionalContext(form) };
    setSaving(true); setFormError(null);
    try { await createDiagnosticSession(firestore, storage, provider, data.vehicleContext, { symptoms, severityDeclared: severity, context, files }); await onCompleted(); }
    catch (cause) { setFormError(cause instanceof Error ? cause.message : 'No se pudo registrar el diagnóstico.'); } finally { setSaving(false); }
  }
  return <form className="diagnostic-form" onSubmit={(event) => { void submit(event); }}><section><span>1 · Evidencias</span><h2>¿Qué notas en el vehículo?</h2><label>Descripción<textarea name="symptoms" placeholder="Describe el ruido, comportamiento o síntoma con tus palabras" /></label><div className="diagnostic-evidence-actions"><button type="button" className={recording ? 'recording' : ''} onClick={() => { void toggleRecording(); }}>{recording ? 'Detener grabación' : 'Grabar audio'}</button><label>Fotografía<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={addPhoto} /></label></div><small>Los audios se comprimen y se detienen automáticamente a los 60 segundos.</small>{files.length > 0 && <div className="diagnostic-local-files">{files.map((file, index) => <span key={`${file.name}-${String(index)}`}>{file.type === 'audio' ? 'Audio' : 'Foto'} · {file.name}<button type="button" onClick={() => { setFiles((current) => current.filter((_, fileIndex) => fileIndex !== index)); }}>Eliminar</button></span>)}</div>}</section>
    <section><span>2 · Contexto</span><h2>¿Cuándo y cómo ocurre?</h2><label>Cuándo ocurre<input name="occurrence" required placeholder="Siempre, de forma intermitente, tras varios minutos…" /></label><label>Motor<select name="temperature" defaultValue="unknown"><option value="unknown">No lo sé</option><option value="cold">Frío</option><option value="hot">Caliente</option><option value="both">En frío y caliente</option></select></label><fieldset><legend>Situación</legend><div className="diagnostic-phase-grid">{PHASES.map((phase) => <label key={phase.value}><input type="checkbox" checked={phases.includes(phase.value)} onChange={(event) => { setPhases((current) => event.target.checked ? [...current, phase.value] : current.filter((item) => item !== phase.value)); }} />{phase.label}</label>)}</div></fieldset><div className="diagnostic-context-grid"><label>Velocidad o revoluciones<input name="speedOrRpm" /></label><label>Testigos<input name="warningLights" /></label><label>Humo<input name="smoke" /></label><label>Olores<input name="odors" /></label><label>Vibraciones<input name="vibrations" /></label><label>Cambios recientes<input name="recentChanges" /></label><label>Modificaciones relacionadas<input name="relatedModifications" /></label><label>Gravedad percibida<select name="severity" defaultValue="medium"><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label></div></section>
    <aside><strong>Contexto completo incluido</strong><p>{data.vehicleContext.vehicle.variantSnapshot.brand} {data.vehicleContext.vehicle.variantSnapshot.model} · {formatNumber(data.vehicleContext.vehicle.mileageKm)} km · {String(data.vehicleContext.installedModifications.filter((item) => item.active).length)} modificaciones registradas{data.vehicleContext.declaredHistory?.seriousBreakdowns ? ' · averías graves declaradas' : ''}.</p></aside>{formError && <p className="diagnostic-error">{formError}</p>}<button className="diagnostic-submit" type="submit" disabled={saving || recording}>{saving ? 'Analizando y guardando…' : 'Analizar evidencias'}</button>
  </form>;
}

function DiagnosticHistory({ data, firestore, storage, onRefresh }: { data: IssuesModuleData; firestore: Firestore; storage: FirebaseStorage; onRefresh: () => Promise<void> }) { const [deleting, setDeleting] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); async function remove(session: DiagnosticSession, evidence: DiagnosticEvidence) { setDeleting(evidence.id); setError(null); try { await deleteDiagnosticEvidence(firestore, storage, session, evidence); await onRefresh(); } catch { setError('No se pudo eliminar el archivo.'); } finally { setDeleting(null); } } return <section className="diagnostic-history"><h2>Historial del vehículo</h2>{error && <p className="diagnostic-error">{error}</p>}{data.sessions.length ? data.sessions.map((session) => <DiagnosticResult key={session.id} session={session} evidence={data.evidenceBySession[session.id] ?? []} deleting={deleting} onDelete={(item) => { void remove(session, item); }} />) : <IssuesEmpty title="Sin diagnósticos" copy="Las sesiones aparecerán aquí después de guardar el primer análisis." />}</section>; }

function DiagnosticResult({ session, evidence, deleting, onDelete }: { session: DiagnosticSession; evidence: DiagnosticEvidence[]; deleting: string | null; onDelete: (evidence: DiagnosticEvidence) => void }) { const result = session.assessment; return <article className="diagnostic-result"><header><div><span>{formatDate(session.startedAt)} · {session.mileageKm !== undefined ? `${formatNumber(session.mileageKm)} km` : ''}</span><h3>{session.title}</h3></div><b>{result ? confidenceLabel(result.confidence) : 'Pendiente'}</b></header>{result ? <><section><span>Resumen del síntoma</span><p>{result.symptomSummary}</p></section><section><span>Posibles causas ordenadas</span>{result.hypotheses.length ? <ol>{result.hypotheses.map((hypothesis) => <li key={hypothesis.title}><strong>{hypothesis.title}</strong><small>Confianza {confidenceLabel(hypothesis.confidence)}</small><p>{hypothesis.explanation}</p>{hypothesis.supportingEvidence.map((item) => <em key={item}>{item}</em>)}</li>)}</ol> : <p>No existe evidencia suficiente para priorizar una causa documentada.</p>}</section><div className="diagnostic-result-grid"><ResultList title="Preguntas adicionales" items={result.additionalQuestions} /><ResultList title="Qué revisar primero" items={result.firstChecks} /><ResultList title="Cuándo detener el vehículo" items={result.stopConditions} /></div><section className={`diagnostic-driving diagnostic-driving--${result.drivingAdvice}`}><span>Circulación y gravedad</span><h4>{drivingLabel(result.drivingAdvice)} · {severityLabel(result.severity)}</h4><p>{result.professionalInspectionRecommendation}</p></section><small className="diagnostic-draft">Resultado {result.reviewStatus === 'ai_draft' ? 'no revisado' : 'revisado'} · Nunca sustituye una inspección presencial.</small></> : <p>Análisis pendiente o interrumpido.</p>}{evidence.filter((item) => item.uploadStatus !== 'deleted').length > 0 && <footer><span>Evidencias privadas</span>{evidence.filter((item) => item.uploadStatus !== 'deleted').map((item) => <button key={item.id} type="button" disabled={deleting === item.id} onClick={() => { onDelete(item); }}>{item.type === 'image' ? 'Fotografía' : item.type === 'audio' ? 'Audio' : 'Texto'} · {deleting === item.id ? 'Eliminando…' : 'Eliminar'}</button>)}</footer>}</article>; }

function ResultList({ title, items }: { title: string; items: string[] }) { return items.length ? <section><span>{title}</span><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></section> : null; }
function IssuesEmpty({ title, copy }: { title: string; copy: string }) { return <article className="garage-empty-module"><span>!</span><h2>{title}</h2><p>{copy}</p></article>; }
function IssuesSkeleton() { return <section className="issues-skeleton" aria-label="Cargando fallos y averías"><span /><span /><span /></section>; }
function stringField(form: FormData, name: string): string { const value = form.get(name); return typeof value === 'string' ? value.trim() : ''; }
function optionalContext(form: FormData): Partial<DiagnosticContext> { const result: Partial<DiagnosticContext> = {}; for (const name of ['speedOrRpm', 'warningLights', 'smoke', 'odors', 'vibrations', 'recentChanges', 'relatedModifications'] as const) { const value = stringField(form, name); if (value) result[name] = value; } return result; }
function isTemperature(value: string): value is DiagnosticContext['engineTemperature'] { return ['cold', 'hot', 'both', 'unknown'].includes(value); }
function isDeclaredSeverity(value: string): value is DiagnosticSession['severityDeclared'] { return ['low', 'medium', 'high', 'urgent'].includes(value); }
function confidenceLabel(value: string) { return { unverified: 'no verificada', low: 'baja', medium: 'media', high: 'alta' }[value] ?? value; }
function severityLabel(value: string) { return { low: 'Baja', medium: 'Media', high: 'Alta', urgent: 'Urgente', unknown: 'Desconocida', safety_critical: 'Crítica' }[value] ?? value; }
function drivingLabel(value: NonNullable<DiagnosticSession['assessment']>['drivingAdvice']) { return { stop_now: 'Detén el vehículo', do_not_drive_until_inspected: 'No circules hasta inspección', only_if_necessary_with_caution: 'Solo si es imprescindible y con cautela', insufficient_information: 'No hay evidencia para afirmar que sea seguro circular' }[value]; }
function formatDate(value: Date) { return new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium' }).format(value); }
function formatNumber(value: number) { return new Intl.NumberFormat('es-ES').format(value); }
