import { z } from 'zod';
import { auth } from '../../../firebase/config';
import type { AIConversation, AIMessage } from '../models';
import type { GarageModuleId } from '../garage/garageTypes';

const date = z.coerce.date();
const conversationSchema = z.object({ id: z.string(), ownerId: z.string(), projectId: z.string(), userVehicleId: z.string(), title: z.string(), status: z.enum(['active', 'archived', 'escalated']), summary: z.string().optional(), summaryVersion: z.number(), lastMessageAt: date.optional(), messageCount: z.number(), schemaVersion: z.number(), createdAt: date, updatedAt: date }).loose();
const replySchema = z.object({ answer: z.string(), confidence: z.enum(['unverified', 'low', 'medium', 'high']), uncertainty: z.string(), needsMoreData: z.boolean(), clarificationQuestions: z.array(z.string()), nextStep: z.string(), references: z.array(z.object({ type: z.string(), id: z.string(), label: z.string() })) });
const messageSchema = z.object({ id: z.string(), ownerId: z.string(), role: z.enum(['user', 'assistant']), content: z.string(), module: z.enum(['vehicle', 'maintenance', 'modifications', 'issues', 'advisor']), runId: z.string().optional(), structured: replySchema.optional(), schemaVersion: z.number(), createdAt: date, updatedAt: date }).loose();

function apiBase(): string { const configured = String(import.meta.env.VITE_API_BASE_URL ?? '').replace(/\/$/, ''); if (typeof window !== 'undefined' && ['localhost', '127.0.0.1', '::1'].includes(window.location.hostname)) return 'http://127.0.0.1:8787'; return configured; }
async function headers(): Promise<Record<string, string>> { const user = auth.currentUser; if (!user) throw new Error('Inicia sesión para usar el Especialista IA.'); return { 'Content-Type': 'application/json', Authorization: `Bearer ${await user.getIdToken()}` }; }
async function payload(response: Response): Promise<unknown> { const value: unknown = await response.json().catch(() => null); if (!response.ok) { const message = typeof value === 'object' && value !== null && 'error' in value ? String(value.error) : 'El Especialista IA no está disponible.'; throw new Error(message); } return value; }

export async function listConversations(vehicleId: string): Promise<AIConversation[]> { const response = await fetch(`${apiBase()}/api/premium/specialist/conversations?vehicleId=${encodeURIComponent(vehicleId)}`, { headers: await headers() }); const parsed = z.object({ conversations: z.array(conversationSchema) }).parse(await payload(response)); return parsed.conversations; }
export async function createConversation(vehicleId: string, title = 'Nueva conversación'): Promise<AIConversation> { const response = await fetch(`${apiBase()}/api/premium/specialist/conversations`, { method: 'POST', headers: await headers(), body: JSON.stringify({ vehicleId, title }) }); return z.object({ conversation: conversationSchema }).parse(await payload(response)).conversation; }
export async function listMessages(vehicleId: string, conversationId: string): Promise<AIMessage[]> { const response = await fetch(`${apiBase()}/api/premium/specialist/messages?vehicleId=${encodeURIComponent(vehicleId)}&conversationId=${encodeURIComponent(conversationId)}`, { headers: await headers() }); return z.object({ messages: z.array(messageSchema) }).parse(await payload(response)).messages; }
export async function sendSpecialistQuestion(vehicleId: string, conversationId: string, question: string, module: GarageModuleId): Promise<{ message: AIMessage; remainingToday: number }> { const response = await fetch(`${apiBase()}/api/premium/specialist/turns`, { method: 'POST', headers: await headers(), body: JSON.stringify({ vehicleId, conversationId, question, module }) }); return z.object({ message: messageSchema, remainingToday: z.number().int().nonnegative(), conversationId: z.string() }).parse(await payload(response)); }
